CREATE SEQUENCE USERS_SEQ;
CREATE TABLE USERS
(
    ID           BIGINT PRIMARY KEY DEFAULT NEXTVAL('USERS_SEQ'),
    NUME         VARCHAR(100) NOT NULL,
    EMAIL        VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD     VARCHAR(255) NOT NULL,
    IS_ENABLED   BOOLEAN            DEFAULT TRUE,
    IS_DELETED   BOOLEAN            DEFAULT FALSE,
    reset_token  VARCHAR(100),
    token_expiry TIMESTAMP,
    VERSION      INTEGER            DEFAULT 0
);

CREATE SEQUENCE ROLE_SEQ;
CREATE TABLE ROLE
(
    ID   BIGINT PRIMARY KEY DEFAULT NEXTVAL('ROLE_SEQ'),
    NAME VARCHAR(100) NOT NULL UNIQUE
);

CREATE SEQUENCE USERS_ROLES_SEQ;
CREATE TABLE USERS_ROLES
(
    ID      BIGINT PRIMARY KEY DEFAULT NEXTVAL('USERS_ROLES_SEQ') USER_ID  BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    CONSTRAINT USERS_ROLES_X_USERS_FK FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT USERS_ROLES_X_ROLE_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID)
);



CREATE SEQUENCE CONTACT_SEQ;
CREATE TABLE CONTACT
(
    id          BIGINT PRIMARY KEY NOT NULL DEFAULT NEXTVAL('CONTACT_SEQ'),
    fk_users    BIGINT             NOT NULL,
    nume        VARCHAR(30)        NOT NULL,
    telefon     INTEGER            NOT NULL,
    email       VARCHAR(200)       NOT NULL,
    serie_sasiu VARCHAR(200),
    descriere   varchar(8000),
    CONSTRAINT users_fk FOREIGN KEY (fk_users) REFERENCES USERS (ID)
);

CREATE SEQUENCE FILE_STORAGE_SEQ;
CREATE TABLE FILE_STORAGE
(
    ID                 BIGINT PRIMARY KEY NOT NULL DEFAULT NEXTVAL('FILE_STORAGE_SEQ'),
    FILE_MD5           VARCHAR(100),
    FILE_UPLOAD_DATE   DATE               NOT NULL,
    FILE_SUBDIR_PATH   VARCHAR(100),
    FILE_ROOT_PATH     VARCHAR(500)       NOT NULL,
    FILE_ORIGINAL_NAME VARCHAR(200)       NOT NULL,
    UTILIZATOR         VARCHAR(200),
    IS_ENABLED         BOOLEAN            NOT NULL DEFAULT TRUE,
    VERSION            INTEGER            NOT NULL DEFAULT 0
);

CREATE SEQUENCE MARCA_SEQ;
CREATE TABLE MARCA
(
    ID           BIGINT PRIMARY KEY DEFAULT NEXTVAL('MARCA_SEQ'),
    NUME         VARCHAR(100) NOT NULL,
    TARA_ORIGINE VARCHAR(100),
    IS_ENABLED   BOOLEAN            DEFAULT TRUE,
    VERSION      INTEGER            DEFAULT 0
);

CREATE SEQUENCE MODEL_SEQ;
CREATE TABLE MODEL
(
    ID            BIGINT PRIMARY KEY DEFAULT NEXTVAL('MODEL_SEQ'),
    FK_MARCA      BIGINT       NOT NULL,
    NUME_MODEL    VARCHAR(100) NOT NULL,
    AN_FABRICATIE INTEGER,
    IS_ENABLED    BOOLEAN            DEFAULT TRUE,
    VERSION       INTEGER            DEFAULT 0,
    CONSTRAINT MODEL_X_MARCA_FK FOREIGN KEY (FK_MARCA) REFERENCES MARCA (ID)
);


CREATE SEQUENCE PROGRAMARE_SEQ;
CREATE TABLE PROGRAMARE
(
    ID                 BIGINT PRIMARY KEY DEFAULT NEXTVAL('PROGRAMARE_SEQ'),
    FK_USER            BIGINT      NOT NULL,
    FK_FILE_STORAGE    BIGINT,
    FK_MARCA           BIGINT      NOT NULL,
    FK_MODEL           BIGINT      NOT NULL,

    NUME               VARCHAR(100) NOT NULL,
    TELEFON            INT         NOT NULL,
    EMAIL              VARCHAR(100) NOT NULL,

    DATA_PROGRAMARE    DATE        NOT NULL,
    ORA_PROGRAMARE     INT         NOT NULL,
    MINUT_PROGRAMARE   INT         NOT NULL,
    SERIE_SASIU        VARCHAR(50) NOT NULL,

    OBSERVATII         VARCHAR(8000),
    IS_CONFIRMED       BOOLEAN            DEFAULT TRUE,
    IS_CANCELED        BOOLEAN            DEFAULT FALSE,

    CREATED_AT         TIMESTAMP          DEFAULT CURRENT_TIMESTAMP,
    VERSION            INTEGER            DEFAULT 0,

    CONSTRAINT PROGRAMARE_X_USERS_FK FOREIGN KEY (FK_USER) REFERENCES USERS (ID),
    CONSTRAINT PROGRAMARE_X_FILE_FK FOREIGN KEY (FK_FILE_STORAGE) REFERENCES FILE_STORAGE (ID),
    CONSTRAINT PROGRAMARE_X_MARCA_FK FOREIGN KEY (FK_MARCA) REFERENCES MARCA (ID),
    CONSTRAINT PROGRAMARE_X_MODEL_FK FOREIGN KEY (FK_MODEL) REFERENCES MODEL (ID)
);
